apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: benefits-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benefits-api
  template:
    metadata:
      labels:
        app: benefits-api
    spec:
      imagePullSecrets:
        - name: dockerhubdemo
      containers:
      - name: benefits-api
        image: fledxy/fledxy_application:9a07b6c9533e3671326f4e76f542988b08497505
        ports:
          - name: benefits-api
            containerPort: 80
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"