apiVersion: v1 
kind: Namespace
metadata: 
  name: benefits-cd
---
apiVersion: v1
kind: Service
metadata:
  name: svc-benefits-api
  namespace: benefits-cd
spec:
  ports:
    - port: 80     # egress port 
      targetPort: 80  # ingress port (containerPort)
  selector:
    app: benefits-api
  type: ClusterIP

