name: Builder Image and Deploy

on:
  push:
    branches:
      - main # Trigger action on pushes to main branch
    paths:
      - "app.api/k8s/**" # Only trigger on changes to the app.api/k8s directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.x'
   
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
   
       - name: Log in to Docker container Registry
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build Docker image
         run: |
             docker build -f app.api/app.Dockerfile  -t fledxy/fledxy_application:${{ github.sha }} .
           
       - name: Push Docker image to Docker hub
         run: |
             docker push fledxy/fledxy_application:${{ github.sha }}
  update_deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update the deployment manifest file
        run: |
          cd app.api/k8s
          kustomize edit set image fledxy/fledxy_application:${{ github.sha }}
          cat kustomize.yaml
          cd ../..
          git pull 
          git add .
          git commit -am "Update image to ${{ github.sha }}"
          git push https://x-access-token:${{ secrets.GH_ACTION_PAT }}github.com/fledxy/benefits_demo.git
   

